# Generated by Django 6.0.2 on 2026-04-15 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_videos',
            name='video',
        ),
        migrations.RemoveField(
            model_name='lessons_image',
            name='image',
        ),
        migrations.AddField(
            model_name='lesson_videos',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/'),
        ),
        migrations.AddField(
            model_name='lessons_image',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lessons/'),
        ),
        migrations.AlterField(
            model_name='lesson_videos',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_videos', to='app.lessons'),
        ),
        migrations.AlterField(
            model_name='lessons_image',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_images', to='app.lessons'),
        ),
    ]
