# Generated by Django 6.0.2 on 2026-04-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_lesson_videos_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_videos',
            name='images',
        ),
        migrations.RemoveField(
            model_name='lessons_image',
            name='video',
        ),
        migrations.AddField(
            model_name='lesson_videos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lessons/'),
        ),
        migrations.AddField(
            model_name='lessons_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/'),
        ),
    ]
