# Generated by Django 6.0.2 on 2026-04-15 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_lesson_videos_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons_collection',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lessons_collection',
            name='video',
        ),
        migrations.AddField(
            model_name='lessons_collection',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='collection_covers/'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.blog_category'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='leaderboard/'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson_videos',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app.lessons'),
        ),
        migrations.AlterField(
            model_name='lesson_videos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/'),
        ),
        migrations.AlterField(
            model_name='lessons_collection',
            name='lesson',
            field=models.ManyToManyField(blank=True, related_name='collections', to='app.lessons'),
        ),
        migrations.AlterField(
            model_name='lessons_collection',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessons_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/images/'),
        ),
        migrations.AlterField(
            model_name='lessons_image',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.lessons'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
